name: انتشار سایت

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: دریافت کد
        uses: actions/checkout@v4

      - name: تنظیم GitHub Pages
        uses: actions/configure-pages@v5

      - name: آماده‌سازی فایل‌های سایت
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: انتشار در GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4